[tool.ruff]
select = ["ALL"]
typing-modules = ["typing"]

ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D107",
    "S104",
    "S603",
    "INP001",
    "TRY400",
]

[tool.ruff.pydocstyle]
convention = "google"